version: '3.9'

services:


  postgres:
    image: postgres:16

    container_name: clinica_postgres

    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: clinicadental

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d


  app:
    build: ./app

    container_name: clinica_backend

    restart: always

    ports:
      - "5000:5000"

    depends_on:
      - postgres


  frontend:
    build: ./sgo_frontend

    container_name: clinica_frontend

    restart: always

    ports:
      - "80:80"

    depends_on:
      - app

volumes:
  postgres_data: