CREATE OR REPLACE VIEW pagos_mensuales_afiliados AS
    SELECT
        A.NUM_A AS NUMERO_ASOCIADO,
        EXTRACT(YEAR FROM P.FECHA_PAGO) AS ANO,
        EXTRACT(MONTH FROM P.FECHA_PAGO) AS MES,
        SUM(P.MONTO) AS MONTO_TOTAL
    FROM PAGO P
    JOIN HISTORIAL H ON P.ID_PAGO = H.ID_PAGO
    JOIN CONSULTA C ON C.NUM_CON = H.NUM_CON
    JOIN PACIENTE PA ON PA.ID_CEDULA = C.ID_CEDULA
    JOIN AFILIADO A ON A.NUM_A = PA.NUM_A
GROUP BY A.NUM_A, EXTRACT(YEAR FROM P.FECHA_PAGO), EXTRACT(MONTH FROM P.FECHA_PAGO);

--3

CREATE OR REPLACE VIEW rebaja_afiliado AS
    SELECT 
        NOMBRE_CONV AS NOMBRE_CONVENIO,
        REBAJA AS "REBAJA[%]"
    FROM CONVENIO;


--4

CREATE OR REPLACE VIEW vista_sucursales_tratamientos AS
SELECT
    S.ID_SUCURSAL,
    S.NOMBRE_S AS SUCURSAL,
    S.CALLE || ' #' || S.NUMERO::TEXT || ', ' || S.CIUDAD AS DIRECCION,
    T.NOM_T AS TRATAMIENTO,
    T.COSTO
FROM SUCURSAL S
JOIN CONSULTORIO C ON S.ID_SUCURSAL = C.ID_SUCURSAL
JOIN ODONTOLOGO O ON O.NUM_COS = C.NUM_COS AND O.ID_SUCURSAL = C.ID_SUCURSAL
JOIN REALIZA R ON O.CEDULA = R.CEDULA
JOIN TRATAMIENTO T ON R.NOM_T=T.NOM_T;


--5

CREATE OR REPLACE VIEW horarioxsucursal AS
    SELECT
        O.NOMO || ' ' || O.APO AS NOMBRE_ODONTOLOGO,
        S.NOMBRE_S AS SUCURSAL,
        TO_CHAR(O.HORARIO_CON, 'HH24:MI') AS HORARIO_CONSULTORIO,
        TO_CHAR(O.HORARIO_SUC, 'HH24:MI') AS HORARIO_SUCURSAL
    FROM ODONTOLOGO O
    JOIN SUCURSAL S ON O.ID_SUCURSAL = S.ID_SUCURSAL;


--6

CREATE OR REPLACE VIEW afiliado_tratamiento AS
    SELECT
        P.NOMP || ' ' || P.APP AS NOMBRE_AFILIADO,
        T.NOM_T AS Nombre_tratamiento,
        T.COSTO AS Costo,
        S.NOMBRE_S AS Sucursal,
        S.CALLE || ' #' || S.NUMERO || ', ' || S.CIUDAD AS DIRECCION,
        H.FECHA_IT,
        H.FECHA_FT
    FROM AFILIADO A
    JOIN PACIENTE P ON A.NUM_A=P.NUM_A
    JOIN CONSULTA C ON P.ID_CEDULA=C.ID_CEDULA
    JOIN HISTORIAL H ON C.NUM_CON = H.NUM_CON
    JOIN TRATAMIENTO T ON H.NOM_T=T.NOM_T
    JOIN SUCURSAL S ON C.ID_SUCURSAL=S.ID_SUCURSAL;


--7

CREATE OR REPLACE VIEW viewodontologos AS
    SELECT
    O.CEDULA,
    O.NOMO || ' ' || O.APO AS NOMBRE_ODONTOLOGO,
    O.ESPECIALIDAD,
    T.NOM_T AS NOMBRE_TRATAMIENTO,
    S.NOMBRE_S AS SUCURSAL
    FROM ODONTOLOGO O
    JOIN CONSULTA C ON C.NUM_COS = O.NUM_COS AND C.ID_SUCURSAL = O.ID_SUCURSAL
    JOIN SUCURSAL S ON S.ID_SUCURSAL=C.ID_SUCURSAL
    JOIN REALIZA R ON O.CEDULA = R.CEDULA
    JOIN TRATAMIENTO T ON R.NOM_T=T.NOM_T;

--8

CREATE OR REPLACE VIEW vista_monto_mensual_tratamiento_sucursal AS
    SELECT
        T.NOM_T AS TRATAMIENTO,
        S.NOMBRE_S AS SUCURSAL,
        EXTRACT(MONTH FROM P.FECHA_PAGO) AS MES,
        EXTRACT(YEAR FROM P.FECHA_PAGO) AS ANIO,
        SUM(P.MONTO) AS MONTO_MENSUAL
    FROM PAGO P
    JOIN HISTORIAL H ON P.ID_PAGO = H.ID_PAGO
    JOIN CONSULTA C ON H.NUM_CON = C.NUM_CON
    JOIN SUCURSAL S ON C.ID_SUCURSAL = S.ID_SUCURSAL
    JOIN TRATAMIENTO T ON H.NOM_T = T.NOM_T
    GROUP BY
        T.NOM_T,
        S.NOMBRE_S,
        EXTRACT(YEAR FROM P.FECHA_PAGO),
        EXTRACT(MONTH FROM P.FECHA_PAGO);

